### ISSUE TITLE
Avali are slightly higher than normal Pawns

### ISSUE THREAD

**Issue by Danimineiro** [NesiTheAvali/RimValiFFA-RW#30]
See image:
Is this intentional?

![image](https://user-images.githubusercontent.com/26352135/213904549-45fcf575-a454-4e21-a38d-45639157a1b9.png)

**Comment by RecompiledBirds** [comment]
This is most likely intentional. In order to not have to make lots of work with small changes to every apparel texture's height, I am using the same positioning as the old mod. Will see once we can spawn them properly in game with the bodytype.
