### ISSUE TITLE
"No Verse.BodyDef named RVFFA_Body" causes loading issues

### ISSUE THREAD

**Issue by Jamesthe1** [NesiTheAvali/RimValiFFA-RW#42]
According to the last update, RimWorld cannot find RVFFA_Body and it causes characters to not load, as well as worlds to not generate. Both Core and RimVali are at the latest version.

[Player.log](https://github.com/RecompiledBirds/RimValiFFA-RW/files/10797344/Player.log)

**Comment by RecompiledBirds** [comment]
This has been fixed in the latest build^^
